# Generated by Django 3.0.5 on 2020-12-06 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='mainapp.Speciality')),
            ],
        ),
    ]
