# Generated by Django 3.0.5 on 2020-12-06 22:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('grade', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma', to='mainapp.Student')),
            ],
        ),
    ]
