# Generated by Django 3.0.5 on 2020-12-06 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_diplomaproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('diploma_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_project_file', to='mainapp.DiplomaProject')),
            ],
        ),
    ]
