# Generated by Django 3.0.5 on 2020-12-06 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201206_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaproject',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_project', to='mainapp.Student'),
        ),
    ]
