# Generated by Django 3.0.5 on 2020-12-06 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201206_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomaproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
